"""Nation entity id -> name for the ids seen on club records (club record +13, person end+9).

The save stores no nation-name table (names come from the install language files), so this is a
hand table. Every id here was verified by reading the 4+ biggest clubs carrying that id in the
2026-27 Spurs save (e.g. 131 = Club Brugge, Genk, Union SG, Standard ...). Unknown ids -> None.
"""
NATION_NAMES = {
    64: 'Kazakhstan', 77: 'Qatar', 78: 'Saudi Arabia', 88: 'United Arab Emirates',
    99: 'Costa Rica', 102: 'El Salvador', 104: 'Guatemala', 107: 'Honduras',
    108: 'Jamaica', 109: 'Mexico', 111: 'Nicaragua', 112: 'Panama',
    119: 'Trinidad and Tobago', 120: 'United States', 126: 'Albania', 128: 'Armenia',
    129: 'Austria', 130: 'Azerbaijan', 131: 'Belgium', 132: 'Belarus',
    133: 'Bosnia and Herzegovina', 134: 'Bulgaria', 135: 'Croatia', 136: 'Cyprus',
    137: 'Czech Republic', 138: 'Denmark', 139: 'England', 140: 'Estonia',
    141: 'Faroe Islands', 142: 'Finland', 143: 'France', 144: 'Georgia', 145: 'Germany',
    146: 'Greece', 147: 'Hungary', 148: 'Iceland', 149: 'Israel', 150: 'Italy',
    153: 'Lithuania', 155: 'North Macedonia', 157: 'Moldova', 158: 'Netherlands',
    159: 'Northern Ireland', 160: 'Norway', 161: 'Poland', 162: 'Portugal',
    163: 'Republic of Ireland', 164: 'Romania', 165: 'Russia', 167: 'Scotland',
    168: 'Slovakia', 169: 'Slovenia', 170: 'Spain', 171: 'Sweden', 172: 'Switzerland',
    173: 'Turkey', 174: 'Ukraine', 176: 'Serbia', 187: 'Argentina', 188: 'Bolivia',
    189: 'Brazil', 190: 'Chile', 191: 'Colombia', 192: 'Ecuador', 193: 'Paraguay',
    194: 'Peru', 195: 'Uruguay', 196: 'Venezuela', 216: 'Gibraltar', 219: 'Kosovo',
    247: 'Montenegro',
}

# Added from the 5 biggest clubs per id (same method; local club names identify the nation).
NATION_NAMES.update({
    0: 'Algeria', 1: 'Angola', 2: 'Benin', 3: 'Botswana', 4: 'Burkina Faso', 5: 'Burundi',
    6: 'Cameroon', 7: 'Cape Verde', 8: 'Central African Republic', 9: 'Chad', 10: 'Djibouti',
    12: 'Equatorial Guinea', 13: 'Ethiopia', 14: 'Gabon', 15: 'Gambia', 16: 'Ghana', 17: 'Guinea',
    18: 'Guinea-Bissau', 19: 'Ivory Coast', 20: 'Kenya', 21: 'Lesotho', 22: 'Liberia',
    23: 'Libya', 24: 'Madagascar', 25: 'Malawi', 26: 'Mali', 27: 'Mauritania', 28: 'Mauritius',
    30: 'Mozambique', 31: 'Namibia', 32: 'Niger', 34: 'Rwanda', 35: 'Sao Tome and Principe',
    36: 'Senegal', 38: 'Sierra Leone', 39: 'Somalia', 40: 'South Africa', 41: 'Sudan',
    42: 'Eswatini', 43: 'Tanzania', 44: 'Congo', 45: 'Togo', 46: 'Tunisia', 47: 'Uganda',
    48: 'DR Congo', 49: 'Zambia', 50: 'Zimbabwe', 51: 'Afghanistan', 52: 'Bahrain', 54: 'Brunei',
    55: 'China', 56: 'Hong Kong', 57: 'India', 58: 'Indonesia', 59: 'Iran', 60: 'Iraq',
    62: 'Jordan', 63: 'Cambodia', 65: 'Kuwait', 66: 'Kyrgyzstan', 67: 'Laos', 68: 'Lebanon',
    69: 'Macau', 70: 'Malaysia', 71: 'Maldives', 73: 'Nepal', 74: 'North Korea', 75: 'Oman',
    76: 'Pakistan', 79: 'Singapore', 81: 'Sri Lanka', 82: 'Syria', 83: 'Taiwan', 84: 'Tajikistan',
    85: 'Thailand', 86: 'Philippines', 87: 'Turkmenistan', 89: 'Uzbekistan', 90: 'Vietnam',
    91: 'Yemen', 92: 'Antigua and Barbuda', 93: 'Aruba', 94: 'Barbados', 95: 'Belize',
    96: 'Bermuda', 98: 'Cayman Islands', 100: 'Cuba', 105: 'Guyana', 106: 'Haiti', 110: 'Curacao',
    113: 'Puerto Rico', 116: 'St Vincent and the Grenadines', 117: 'Suriname', 118: 'Bahamas',
    127: 'Andorra', 151: 'Latvia', 154: 'Luxembourg', 156: 'Malta', 166: 'San Marino',
    178: 'Cook Islands', 179: 'Fiji', 180: 'New Zealand', 181: 'Papua New Guinea',
    182: 'Solomon Islands', 183: 'Tahiti', 184: 'Tonga', 185: 'Vanuatu', 186: 'Samoa',
    197: 'Palestine', 202: 'Mongolia', 204: 'Eritrea', 206: 'British Virgin Islands',
    207: 'Montserrat', 208: 'US Virgin Islands', 209: 'Turks and Caicos', 211: 'Bhutan',
    212: 'Dominican Republic', 215: 'Kiribati', 234: 'Comoros', 236: 'Timor-Leste',
    240: 'South Sudan',
    205: 'Anguilla', 225: 'French Guiana', 226: 'Guadeloupe', 227: 'Martinique', 230: 'Reunion',
    231: 'Mayotte',
    11: 'Egypt', 29: 'Morocco', 33: 'Nigeria', 97: 'Canada', 61: 'Japan', 80: 'South Korea',
    177: 'Australia', 175: 'Wales',  # ids from the GUI's verified table
})


def nation_name(nation_id):
    return NATION_NAMES.get(nation_id)


# ISO 3166-1 alpha-2 per nation name -> flag emoji (regional-indicator pairs). GB home nations use
# tag-sequence flags (no alpha-2 of their own); keyed by id because Wales has no NATION_NAMES entry.
_ISO = {
    'Algeria': 'DZ',
    'Angola': 'AO',
    'Benin': 'BJ',
    'Botswana': 'BW',
    'Burkina Faso': 'BF',
    'Burundi': 'BI',
    'Cameroon': 'CM',
    'Cape Verde': 'CV',
    'Central African Republic': 'CF',
    'Chad': 'TD',
    'Djibouti': 'DJ',
    'Egypt': 'EG',
    'Equatorial Guinea': 'GQ',
    'Ethiopia': 'ET',
    'Gabon': 'GA',
    'Gambia': 'GM',
    'Ghana': 'GH',
    'Guinea': 'GN',
    'Guinea-Bissau': 'GW',
    'Ivory Coast': 'CI',
    'Kenya': 'KE',
    'Lesotho': 'LS',
    'Liberia': 'LR',
    'Libya': 'LY',
    'Madagascar': 'MG',
    'Malawi': 'MW',
    'Mali': 'ML',
    'Mauritania': 'MR',
    'Mauritius': 'MU',
    'Morocco': 'MA',
    'Mozambique': 'MZ',
    'Namibia': 'NA',
    'Niger': 'NE',
    'Nigeria': 'NG',
    'Rwanda': 'RW',
    'Sao Tome and Principe': 'ST',
    'Senegal': 'SN',
    'Sierra Leone': 'SL',
    'Somalia': 'SO',
    'South Africa': 'ZA',
    'Sudan': 'SD',
    'Eswatini': 'SZ',
    'Tanzania': 'TZ',
    'Congo': 'CG',
    'Togo': 'TG',
    'Tunisia': 'TN',
    'Uganda': 'UG',
    'DR Congo': 'CD',
    'Zambia': 'ZM',
    'Zimbabwe': 'ZW',
    'Afghanistan': 'AF',
    'Bahrain': 'BH',
    'Brunei': 'BN',
    'China': 'CN',
    'Hong Kong': 'HK',
    'India': 'IN',
    'Indonesia': 'ID',
    'Iran': 'IR',
    'Iraq': 'IQ',
    'Japan': 'JP',
    'Jordan': 'JO',
    'Cambodia': 'KH',
    'Kazakhstan': 'KZ',
    'South Korea': 'KR',
    'Kuwait': 'KW',
    'Kyrgyzstan': 'KG',
    'Laos': 'LA',
    'Lebanon': 'LB',
    'Macau': 'MO',
    'Malaysia': 'MY',
    'Maldives': 'MV',
    'Nepal': 'NP',
    'North Korea': 'KP',
    'Oman': 'OM',
    'Pakistan': 'PK',
    'Qatar': 'QA',
    'Saudi Arabia': 'SA',
    'Singapore': 'SG',
    'Sri Lanka': 'LK',
    'Syria': 'SY',
    'Taiwan': 'TW',
    'Tajikistan': 'TJ',
    'Thailand': 'TH',
    'Philippines': 'PH',
    'Turkmenistan': 'TM',
    'United Arab Emirates': 'AE',
    'Uzbekistan': 'UZ',
    'Vietnam': 'VN',
    'Yemen': 'YE',
    'Antigua and Barbuda': 'AG',
    'Aruba': 'AW',
    'Barbados': 'BB',
    'Belize': 'BZ',
    'Bermuda': 'BM',
    'Canada': 'CA',
    'Cayman Islands': 'KY',
    'Costa Rica': 'CR',
    'Cuba': 'CU',
    'El Salvador': 'SV',
    'Guatemala': 'GT',
    'Guyana': 'GY',
    'Haiti': 'HT',
    'Honduras': 'HN',
    'Jamaica': 'JM',
    'Mexico': 'MX',
    'Curacao': 'CW',
    'Nicaragua': 'NI',
    'Panama': 'PA',
    'Puerto Rico': 'PR',
    'St Vincent and the Grenadines': 'VC',
    'Suriname': 'SR',
    'Bahamas': 'BS',
    'Trinidad and Tobago': 'TT',
    'United States': 'US',
    'Albania': 'AL',
    'Andorra': 'AD',
    'Armenia': 'AM',
    'Austria': 'AT',
    'Azerbaijan': 'AZ',
    'Belgium': 'BE',
    'Belarus': 'BY',
    'Bosnia and Herzegovina': 'BA',
    'Bulgaria': 'BG',
    'Croatia': 'HR',
    'Cyprus': 'CY',
    'Czech Republic': 'CZ',
    'Denmark': 'DK',
    'Estonia': 'EE',
    'Faroe Islands': 'FO',
    'Finland': 'FI',
    'France': 'FR',
    'Georgia': 'GE',
    'Germany': 'DE',
    'Greece': 'GR',
    'Hungary': 'HU',
    'Iceland': 'IS',
    'Israel': 'IL',
    'Italy': 'IT',
    'Latvia': 'LV',
    'Lithuania': 'LT',
    'Luxembourg': 'LU',
    'North Macedonia': 'MK',
    'Malta': 'MT',
    'Moldova': 'MD',
    'Netherlands': 'NL',
    'Norway': 'NO',
    'Poland': 'PL',
    'Portugal': 'PT',
    'Republic of Ireland': 'IE',
    'Romania': 'RO',
    'Russia': 'RU',
    'San Marino': 'SM',
    'Slovakia': 'SK',
    'Slovenia': 'SI',
    'Spain': 'ES',
    'Sweden': 'SE',
    'Switzerland': 'CH',
    'Turkey': 'TR',
    'Ukraine': 'UA',
    'Serbia': 'RS',
    'Australia': 'AU',
    'Cook Islands': 'CK',
    'Fiji': 'FJ',
    'New Zealand': 'NZ',
    'Papua New Guinea': 'PG',
    'Solomon Islands': 'SB',
    'Tahiti': 'PF',
    'Tonga': 'TO',
    'Vanuatu': 'VU',
    'Samoa': 'WS',
    'Argentina': 'AR',
    'Bolivia': 'BO',
    'Brazil': 'BR',
    'Chile': 'CL',
    'Colombia': 'CO',
    'Ecuador': 'EC',
    'Paraguay': 'PY',
    'Peru': 'PE',
    'Uruguay': 'UY',
    'Venezuela': 'VE',
    'Gibraltar': 'GI',
    'Kosovo': 'XK',
    'Montenegro': 'ME',
    'Palestine': 'PS',
    'Mongolia': 'MN',
    'Eritrea': 'ER',
    'British Virgin Islands': 'VG',
    'Montserrat': 'MS',
    'US Virgin Islands': 'VI',
    'Turks and Caicos': 'TC',
    'Bhutan': 'BT',
    'Dominican Republic': 'DO',
    'Kiribati': 'KI',
    'Comoros': 'KM',
    'Timor-Leste': 'TL',
    'South Sudan': 'SS',
    'Anguilla': 'AI',
    'French Guiana': 'GF',
    'Guadeloupe': 'GP',
    'Martinique': 'MQ',
    'Reunion': 'RE',
    'Mayotte': 'YT',
}
_HOME_FLAG = {  # id -> subdivision tag
    139: 'gbeng', 159: 'gbnir', 167: 'gbsct', 175: 'gbwls',
}


def nation_flag(nation_id):
    """Flag emoji for a nation id, or None when no valid code is known."""
    tag = _HOME_FLAG.get(nation_id)
    if tag:
        return '\U0001F3F4' + ''.join(chr(0xE0000 + ord(c)) for c in tag) + '\U000E007F'
    code = _ISO.get(NATION_NAMES.get(nation_id))
    if not code:
        return None
    return ''.join(chr(0x1F1E6 + ord(c) - 65) for c in code)


STATUS_NAMES = {1: 'Professional', 2: 'Semi-professional', 3: 'Amateur'}
